[[module.imports]]
path = "github.com/desandro/imagesloaded"
[[module.imports.mounts]]
source = "imagesloaded.pkgd.min.js"
target = "assets/hb/modules/gordolin/imagesloaded/imagesloaded.pkgd.min.js"

[[module.imports]]
path = "github.com/desandro/masonry"
[[module.imports.mounts]]
source = "dist/masonry.pkgd.min.js"
target = "assets/hugomods/masonry-js/masonry.pkgd.min.js"